= Cas pratique ( VLAN et Packet Tracer )

== Création des VLANs et assignation des dispositifs :

=== VLAN 10 : 

Contiendra les ordinateurs de Thomas et Claudia, une imprimante, et un serveur d'application (Intranet).

=== VLAN 20 : 

Contiendra les ordinateurs de Roger et Sarah, une autre imprimante, et le même serveur d'application.

=== Étape 1 : Création des VLANs


Accéder au switch et créer les VLANs pour segmenter le réseau.

[source, bash]
----
Switch> enable
Switch# configure terminal
----

=== ...

Créer le VLAN 10 pour Thomas, Claudia, leur imprimante et le serveur.

[source, bash]
----
Switch(config)# vlan 10
Switch(config-vlan)# name VLAN_Thomas_Claudia
----

=== ...

Créer le VLAN 20 pour Roger, Sarah, leur imprimante et le même serveur.

[source, bash]
----
Switch(config)# vlan 20
Switch(config-vlan)# name VLAN_Roger_Sarah
----

=== Étape 2 : 

Assigner les ports des ordinateurs et imprimantes aux VLANs

=== ...

Assigner les ordinateurs de Thomas et Claudia au VLAN 10 :

=== ...

Pour Thomas (port FastEthernet 0/1) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/1
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----

=== ...

Pour Claudia (port FastEthernet 0/2) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/2
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----


Assigner l'imprimante du VLAN 10 (port FastEthernet 0/3) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/3
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----

=== ...

Assigner les ordinateurs de Roger et Sarah au VLAN 20 :

=== ...

Pour Roger (port FastEthernet 0/4) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/4
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----

=== ...

Pour Sarah (port FastEthernet 0/5) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/5
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----

=== ...

Assigner l'imprimante du VLAN 20 (port FastEthernet 0/6) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/6
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----


=== Étape 3 : Configuration du serveur d'application partagé


Le serveur d'application doit être accessible par les deux VLANs. 

=== ...

Pour ce faire, vous pouvez :

=== ...

Placer le serveur d'application dans un troisième VLAN (VLAN 30) ou dans un réseau central.

=== ...

Exemple de configuration du port du serveur d'application (port FastEthernet 0/7) :


[source, bash]
----
Switch(config)# interface fastEthernet 0/7
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 30
----

Configurer le routage inter-VLAN pour permettre aux deux VLANs (VLAN 10 et VLAN 20) d'accéder au serveur sur VLAN 30.

=== Étape 4 : Routage inter-VLAN (via un switch multicouche ou un routeur)

Pour que les ordinateurs dans les VLANs 10 et 20 puissent accéder au serveur d'application (sur VLAN 30), vous devez activer le routage inter-VLAN.

=== ...

Configurer un switch multicouche (par exemple, un Cisco 3560) pour activer le routage entre les VLANs :

=== ...

Configuration de l'interface VLAN 10 (pour le réseau de Thomas et Claudia) :

[source, bash]
----
Switch(config)# interface vlan 10
Switch(config-if)# ip address 192.168.10.1 255.255.255.0
----

=== ...

Configuration de l'interface VLAN 20 (pour le réseau de Roger et Sarah) :

[source, bash]
----
Switch(config)# interface vlan 20
Switch(config-if)# ip address 192.168.20.1 255.255.255.0
----

=== ...

Configuration de l'interface VLAN 30 (pour le serveur d'application) :

[source, bash]
----
Switch(config)# interface vlan 30
Switch(config-if)# ip address 192.168.30.1 255.255.255.0
----

=== ...

Activer le routage inter-VLAN sur le switch :

[source, bash]
----
Switch(config)# ip routing
----

=== ...

Configurer les ordinateurs pour utiliser la passerelle par défaut (les adresses IP du switch dans chaque VLAN) :

=== ...

Thomas et Claudia (VLAN 10) utiliseront 192.168.10.1 comme passerelle.

=== ...

Roger et Sarah (VLAN 20) utiliseront 192.168.20.1 comme passerelle.

=== ...

Le serveur d'application dans le VLAN 30 aura une passerelle 192.168.30.1.







